"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['fridge_data_organizer.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/wei/Downloads/fridge_data_organizer-main/image/icon.icns',
           'includes': ['tkinter', 'pandas', 'tempfile','base64','zlib','openpyxl','jinja2']
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
